// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NfvoUIClient is the client API for NfvoUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NfvoUIClient interface {
	// ListVsfmSpecs returns a list of VSF Manager(s) that can be started through the UI.
	ListVsfmSpecs(ctx context.Context, in *ListVsfmSpecsRequest, opts ...grpc.CallOption) (NfvoUI_ListVsfmSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type nfvoUIClient struct {
	cc grpc.ClientConnInterface
}

func NewNfvoUIClient(cc grpc.ClientConnInterface) NfvoUIClient {
	return &nfvoUIClient{cc}
}

func (c *nfvoUIClient) ListVsfmSpecs(ctx context.Context, in *ListVsfmSpecsRequest, opts ...grpc.CallOption) (NfvoUI_ListVsfmSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NfvoUI_ServiceDesc.Streams[0], "/v1.NfvoUI/ListVsfmSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &nfvoUIListVsfmSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NfvoUI_ListVsfmSpecsClient interface {
	Recv() (*ListVsfmSpecsResponse, error)
	grpc.ClientStream
}

type nfvoUIListVsfmSpecsClient struct {
	grpc.ClientStream
}

func (x *nfvoUIListVsfmSpecsClient) Recv() (*ListVsfmSpecsResponse, error) {
	m := new(ListVsfmSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nfvoUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.NfvoUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NfvoUIServer is the server API for NfvoUI service.
// All implementations must embed UnimplementedNfvoUIServer
// for forward compatibility
type NfvoUIServer interface {
	// ListVsfmSpecs returns a list of VSF Manager(s) that can be started through the UI.
	ListVsfmSpecs(*ListVsfmSpecsRequest, NfvoUI_ListVsfmSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedNfvoUIServer()
}

// UnimplementedNfvoUIServer must be embedded to have forward compatible implementations.
type UnimplementedNfvoUIServer struct {
}

func (UnimplementedNfvoUIServer) ListVsfmSpecs(*ListVsfmSpecsRequest, NfvoUI_ListVsfmSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListVsfmSpecs not implemented")
}
func (UnimplementedNfvoUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedNfvoUIServer) mustEmbedUnimplementedNfvoUIServer() {}

// UnsafeNfvoUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NfvoUIServer will
// result in compilation errors.
type UnsafeNfvoUIServer interface {
	mustEmbedUnimplementedNfvoUIServer()
}

func RegisterNfvoUIServer(s grpc.ServiceRegistrar, srv NfvoUIServer) {
	s.RegisterService(&NfvoUI_ServiceDesc, srv)
}

func _NfvoUI_ListVsfmSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVsfmSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NfvoUIServer).ListVsfmSpecs(m, &nfvoUIListVsfmSpecsServer{stream})
}

type NfvoUI_ListVsfmSpecsServer interface {
	Send(*ListVsfmSpecsResponse) error
	grpc.ServerStream
}

type nfvoUIListVsfmSpecsServer struct {
	grpc.ServerStream
}

func (x *nfvoUIListVsfmSpecsServer) Send(m *ListVsfmSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NfvoUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NfvoUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NfvoUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NfvoUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NfvoUI_ServiceDesc is the grpc.ServiceDesc for NfvoUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NfvoUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NfvoUI",
	HandlerType: (*NfvoUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _NfvoUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListVsfmSpecs",
			Handler:       _NfvoUI_ListVsfmSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sfvo-ui.proto",
}
